#
###################################
# Site wide configuration
####################################
#
title: The good things come to those who hustle
email: huynguyennovem@gmail.com
description: The good things come to those who hustle
url: # the base hostname & protocol for your site
keywords: ["blog", "developer", "android", "application"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Ho_Chi_Minh
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Nguyen Quang Huy
  avatar: avatar.jpg
  job: "Mobile Developer"
  bio: "The good things come to those who hustle"
  email:
  disqus-shortname: The good things come to those who hustle
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: huynguyennovem
  gitlab: #username
  stackoverflow: 5921933/huy-nguyen
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

remote_theme: pages-themes/architect
theme: jekyll-theme-architect
