site_name: Huy Nguyen Blog
nav:
  - Home: index.md
  - Posts: posts.md
  - About: about.md
  - Community Activities: community_activities.md
  - Projects and packages: projects_packages.md
  - Contributions: contributions.md
theme: readthedocs