site_name: Huy Nguyen Blog
nav:
  - Home: index.md
  - Posts: posts.md
  - About: about.md
  - Community Activities: community_activities.md
  - Projects and packages: projects_packages.md
  - Contributions: contributions.md
theme: readthedocs
extra:
  analytics:
    provider: google
    property: G-RJT4VPTE10
    feedback:
      title: Was my blog helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This blog was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This blog could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this blog by
            using our <a href="https://github.com/huynguyennovem/huynguyennovem.github.io/issues" target="_blank" rel="noopener">feedback form</a>.